data:
  N_clusters: 2
  isRing: true
hps:
  hidden_dim: 64
  num_conv_layers: 3
  final_cnn_relu: true
  learn_init: true 
  k_slots: 3
  query_dim: 64 
  softmax_T: default
  n_iter: 3
opt:
  Ntrain: 1000000
  bs: 256
