data:
  N_clusters: 2
  isRing: true
  logE: true
hps:
  hidden_dim: 16
  k_slots: 3
  query_dim: 128 
  softmax_T: default
  pos_inpts: true 
  learn_init: true
opt:
  lr: 0.75e-4
  Ntrain: 1000000
  bs: 256
