data:
  N_clusters: 2
  isRing: true
hps:
  final_cnn_relu: true
  hidden_dim: 64
  k_slots: 3
  learn_init: true
  n_iter: 3
  num_conv_layers: 3
  query_dim: 64
  softmax_T: default
opt:
  Ntrain: 1000000
  bs: 256
  lr: 0.0003
